### ISSUE TITLE
Node.js - Key Condition Expressions with AWS SDK for Node.js

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#10]
How we do this section I am open for debate, so please chime in. How would you want to see examples for the "Working with Queries" section. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html

Create the following example files one per topic:

- A query with begins_with() on the SK.
- A query having the following examples: a = b, a < b, a <= b, a > b, a >= b, a BETWEEN b AND c. Show at least one or more of the examples should use an expression-attribute-value.

**Comment by synchrophoto** [comment]
Make sure when doing queries that there is always a check for "LastEvaluatedKey" in the response. If so, you know you did not get the full results of the query and if you need more, you have to use the pagination example. I would recommend adding this as a comment in the code actually.

**Comment by jprivillaso** [comment]
Hello @synchrophoto 
I want to implement this PR. I will be working on it in my forked repo until somehow I can be assigned to it.
Thanks

**Comment by jprivillaso** [comment]
@synchrophoto We intend to add examples to perform the abovementioned operations: equals, greater than, less than, etc. 

I believe that with the current `sort key` we won't be able to cover all these cases. For example, it would be nice to show people how to query dates using the `between` operator. Should we create a GSI in this case? Because this example uses the `Thread` table and its sort key is `Subject`. 

What do you think?

**Comment by jprivillaso** [comment]
Ah! Nevermind. I see that the Reply table has a ReplyDateTime that can be used for the `between` operation :)

**Comment by jprivillaso** [comment]
Can we close this issue? 
The pull request has been merged
