### ISSUE TITLE
Node.js - Create code examples for general table level operations using the Node.js SDK

### ISSUE THREAD

**Issue by synchrophoto** [synchrophoto/DynamoDB-SDK-examples#4]
Create code examples for the following table level operations:
- Create table in provisioned capacity mode
- Create table in on-demand capacity mode
- Change table's provisioned capacity to add more capacity.
- Enable auto-scaling on a table set to provisioned capacity
- Update auto-scaling settings on a table set to provisioned capacity
- Disable auto-scaling on a provisioned capacity mode
- Describe limits
- Describe table
- List tables
- Change provisioned capacity mode table to on-demand mode
- Change on-demand mode table to provisioned and then add auto-scaling policy
- Enable streams on a table
- Delete a table

**Comment by TLaue** [comment]
I will start with this one. Any conventions to follow?

**Comment by synchrophoto** [comment]
Good question, I am not sure. What are your thoughts?

**Comment by TLaue** [comment]
I am trying to follow the naming conventions (variables...) used in the python examples to make the code as consistent as possible independent of the actual language. Otherwise I would suggest to use double quotes for strings, to use semicolons and ES6 and above language featues like (async/await...)  - but this is pure personal preference

**Comment by johanrin** [comment]
I'm closing this issue because PR already merged in #23
